import { describe, expect, it } from 'vitest';
import { compareSimCommands, createWorld, queueRecruitment } from '../../src/sim';
import type { RecruitCommand, WorldState } from '../../src/sim';
const recruit=(sequence:number,faction:'victoria'|'obsidian',unitKind:'pawn'|'knight'|'bishop'|'rook'):RecruitCommand=>({type:'recruit',sequence,issuedTick:0,faction,unitKind});
function crown(world:WorldState,amount:number):WorldState{return {...world,economy:{crownPower:{...world.economy.crownPower,victoria:amount}}};}
function own(world:WorldState,ids:string[]):WorldState{const nodes={...world.territory.nodes};for(const id of ids)nodes[id]={...nodes[id]!,owner:'victoria'};return {...world,territory:{nodes}};}
describe('production queue',()=>{
 it('accepts Pawn, spends immediately, reserves FIFO and increments ordinal',()=>{const r=queueRecruitment(crown(createWorld(),50),recruit(1,'victoria','pawn'));expect(r.state.economy.crownPower.victoria).toBe(40);expect(r.state.production.queues.victoria[0]!.id).toBe('victoria-recruit-1');expect(r.state.production.nextEntryOrdinal.victoria).toBe(2);expect(r.events.map(e=>e.type)).toEqual(['crown.spent','production.queued']);const r2=queueRecruitment(r.state,recruit(2,'victoria','pawn'));expect(r2.state.production.queues.victoria.map(e=>e.id)).toEqual(['victoria-recruit-1','victoria-recruit-2']);});
 it('enforces unlock, Crown, capacity and hard caps without mutation',()=>{expect(queueRecruitment(crown(createWorld(),100),recruit(1,'victoria','knight')).events[0]).toMatchObject({type:'production.rejected',reason:'locked'});const poor=createWorld();const insufficient=queueRecruitment(poor,recruit(1,'victoria','pawn'));expect(insufficient.events[0]).toMatchObject({reason:'insufficient_crown'});expect(insufficient.state).toBe(poor);let w=crown(createWorld(Array.from({length:6},(_,i)=>({id:`p${i}`,faction:'victoria' as const,kind:'pawn' as const,position:{x:i,y:0}}))),100);expect(queueRecruitment(w,recruit(1,'victoria','pawn')).events[0]).toMatchObject({reason:'capacity_exceeded'});let cap=own(crown(createWorld(),100),['minor-nw','minor-ne']);cap=queueRecruitment(cap,recruit(1,'victoria','knight')).state;cap=queueRecruitment(cap,recruit(2,'victoria','knight')).state;expect(queueRecruitment(cap,recruit(3,'victoria','knight')).events[0]).toMatchObject({reason:'piece_cap_reached'});});
 it('relocks recruitment after territory loss without deleting living units or queues',()=>{let w=own(crown(createWorld([{id:'live-k',faction:'victoria',kind:'knight',position:{x:0,y:0}}]),100),['minor-nw','minor-ne']);w=queueRecruitment(w,recruit(1,'victoria','knight')).state;const nodes={...w.territory.nodes,'minor-ne':{...w.territory.nodes['minor-ne']!,owner:null}};w={...w,territory:{nodes}};const r=queueRecruitment(w,recruit(2,'victoria','knight'));expect(r.events[0]).toMatchObject({reason:'locked'});expect(r.state.units['live-k']).toBeDefined();expect(r.state.production.queues.victoria).toHaveLength(1);});
 it('sorts mixed commands by sequence, actor key, then command type',()=>{const cmds:any[]=[recruit(2,'victoria','pawn'),{type:'move',sequence:1,issuedTick:0,unitId:'b',to:{x:1,y:1}},{type:'attack',sequence:1,issuedTick:0,unitId:'a',targetId:'x'}];expect([...cmds].sort(compareSimCommands).map(c=>c.type)).toEqual(['attack','move','recruit']);});
});
